In [1]:
!pip install numpy


[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
array=np.array(10)

In [4]:
print(array)

10


In [5]:
type(array)

numpy.ndarray

In [6]:
#zero dimension array
zeroD=np.array(10)

In [7]:
print(zeroD)

10


In [8]:
print(zeroD.ndim)

0


In [12]:
#one dimension array
oneD=np.array([1,2,3,4,5])

In [10]:
print(oneD)

[1 2 3 4 5]


In [11]:
print(oneD.ndim)

1


In [15]:
twoD=np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

In [16]:
print(twoD)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
print(twoD.ndim)

2


In [18]:
#more than 2 dimension called tensor
tensor=np.array([[[1,2,3],
                  [4,5,6]],
                 [[1,2,3],
                  [4,5,6]]])

In [19]:
print(tensor)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [20]:
print(tensor.ndim)

3
