In [1]:
import numpy as np

In [2]:
oned=np.array([2,4,6,8])
twod=np.array([[3,6,9,12],
               [4,8,12,16]])

In [3]:
oned

array([2, 4, 6, 8])

In [4]:
twod

array([[ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

In [6]:
oned.ndim

1

In [7]:
twod.ndim

2

In [8]:
oned[0]

2

In [10]:
oned[2]

6

In [11]:
twod[0,1]

6

In [12]:
twod[1,3]

16

In [13]:
print(oned)

[2 4 6 8]


In [14]:

print(twod)

[[ 3  6  9 12]
 [ 4  8 12 16]]


In [15]:
oned[1:]

array([4, 6, 8])

In [16]:
for a in oned:
    print(a)

2
4
6
8


In [18]:
for a in oned:
    if a%2==0:
        print(a)
    else:
        print("Hi")


2
4
6
8


In [19]:
twod[1,1:]

array([ 8, 12, 16])

In [20]:
twod[1:,1]

array([8])

In [21]:
for a in twod:
    print(a*5)

[15 30 45 60]
[20 40 60 80]
