In [2]:
w1,w2,w3=0.3,0.2,0.5

In [3]:
kanto_temp=73
kanto_rainfall=67
kanto_humidity=43

In [4]:
kanto_my=kanto_temp*w1+kanto_rainfall*w2+kanto_humidity
print("The expected yield in kanto region is {} tonnes of hectares".format(kanto_my))

The expected yield in kanto region is 78.3 tonnes of hectares


In [5]:
import numpy as np

In [6]:
kanto=np.array([73,67,43])

In [7]:
kanto

array([73, 67, 43])

In [14]:
weights=np.array([0.3,0.2,0.5])

In [15]:
np.dot(kanto,weights)

56.8

In [16]:
np.cross(kanto,weights)

array([ 24.9, -23.6,  -5.5])

In [17]:
kanto*weights

array([21.9, 13.4, 21.5])

In [18]:
(kanto*weights).sum()

56.8

In [19]:
arr1=list(range(1000))
arr2=list(range(1000,2000))

In [20]:
arr1_np=np.array(arr1)
arr2_np=np.array(arr2)

In [21]:
%%time
result=0
for x,y in zip(arr1,arr2):
    result+=x*y
result      

CPU times: total: 0 ns
Wall time: 0 ns


832333500

In [23]:
%%time
np.dot(arr1_np,arr2_np)

CPU times: total: 0 ns
Wall time: 0 ns


832333500

In [26]:
arr4=np.array([[17,25,25],[12,54,21],[13,64,24]])

In [27]:
arr4.shape

(3, 3)

In [28]:
np.matmul(arr4,weights)

array([22.6, 24.9, 28.7])

In [29]:
arr4.dtype

dtype('int32')

In [30]:
arr4 @ weights

array([22.6, 24.9, 28.7])

In [32]:
mn=np.genfromtxt("Stores.csv",delimiter =",",skip_header=1)

In [33]:
mn

array([[1.000e+00, 1.659e+03, 1.961e+03, 5.300e+02, 6.649e+04],
       [2.000e+00, 1.461e+03, 1.752e+03, 2.100e+02, 3.982e+04],
       [3.000e+00, 1.340e+03, 1.609e+03, 7.200e+02, 5.401e+04],
       ...,
       [8.940e+02, 1.200e+03, 1.436e+03, 1.060e+03, 7.644e+04],
       [8.950e+02, 1.299e+03, 1.560e+03, 7.700e+02, 9.661e+04],
       [8.960e+02, 1.174e+03, 1.429e+03, 1.110e+03, 5.434e+04]])

In [34]:
mn.shape

(896, 5)

In [38]:
weights.shape

(3,)

In [39]:
weights.reshape(896,5)

ValueError: cannot reshape array of size 3 into shape (896,5)

In [ ]:
results= np.concatenate((mn,arr4.reshape(10000,1),axis=1))#because we have no same shape thats why we cannot concatenate

In [40]:
help(np.savetxt)

Help on function savetxt in module numpy:

savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='\n', header='', footer='', comments='# ', encoding=None)
    Save an array to a text file.
    
    Parameters
    ----------
    fname : filename or file handle
        If the filename ends in ``.gz``, the file is automatically saved in
        compressed gzip format.  `loadtxt` understands gzipped files
        transparently.
    X : 1D or 2D array_like
        Data to be saved to a text file.
    fmt : str or sequence of strs, optional
        A single format (%10.5f), a sequence of formats, or a
        multi-format string, e.g. 'Iteration %d -- %10.5f', in which
        case `delimiter` is ignored. For complex `X`, the legal options
        for `fmt` are:
    
        * a single specifier, `fmt='%.4e'`, resulting in numbers formatted
          like `' (%s+%sj)' % (fmt, fmt)`
        * a full string specifying every real and imaginary part, e.g.
          `' %.4e %+.4ej %.4e %+.4ej %.4

In [46]:
np.savetxt("mn.txt",mn,fmt=%.2f,header='temperature,rainfall,comments=" ",delimiter=",")

SyntaxError: invalid decimal literal (2483556005.py, line 1)